project:
  type: book

book:
  title: "project_test"
  author: "Norah Jones"
  date: "6/23/2024"


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

profile:
  default: intro
  group: 
    - [intro, summary]



